#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -std=c++20 -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/xmlpretty

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/xmlpretty

OBJ_DEBUG = $(OBJDIR_DEBUG)/__/CommonCpp/KSDateTime/KSDateTime.o $(OBJDIR_DEBUG)/__/CommonCpp/KSEventLog/KSEventLog.o $(OBJDIR_DEBUG)/__/CommonCpp/KSUtils/KSUtil.o $(OBJDIR_DEBUG)/__/CommonCpp/KSUtils/KSUtil20.o $(OBJDIR_DEBUG)/__/CommonCpp/Platform/Linux/Platform.o $(OBJDIR_DEBUG)/__/CommonCpp/strfmt.o $(OBJDIR_DEBUG)/main.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/__/CommonCpp/KSDateTime/KSDateTime.o $(OBJDIR_RELEASE)/__/CommonCpp/KSEventLog/KSEventLog.o $(OBJDIR_RELEASE)/__/CommonCpp/KSUtils/KSUtil.o $(OBJDIR_RELEASE)/__/CommonCpp/KSUtils/KSUtil20.o $(OBJDIR_RELEASE)/__/CommonCpp/Platform/Linux/Platform.o $(OBJDIR_RELEASE)/__/CommonCpp/strfmt.o $(OBJDIR_RELEASE)/main.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/__/CommonCpp/KSDateTime || mkdir -p $(OBJDIR_DEBUG)/__/CommonCpp/KSDateTime
	test -d $(OBJDIR_DEBUG)/__/CommonCpp/KSEventLog || mkdir -p $(OBJDIR_DEBUG)/__/CommonCpp/KSEventLog
	test -d $(OBJDIR_DEBUG)/__/CommonCpp/KSUtils || mkdir -p $(OBJDIR_DEBUG)/__/CommonCpp/KSUtils
	test -d $(OBJDIR_DEBUG)/__/CommonCpp/Platform/Linux || mkdir -p $(OBJDIR_DEBUG)/__/CommonCpp/Platform/Linux
	test -d $(OBJDIR_DEBUG)/__/CommonCpp || mkdir -p $(OBJDIR_DEBUG)/__/CommonCpp
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/__/CommonCpp/KSDateTime/KSDateTime.o: ../CommonCpp/KSDateTime/KSDateTime.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ../CommonCpp/KSDateTime/KSDateTime.cpp -o $(OBJDIR_DEBUG)/__/CommonCpp/KSDateTime/KSDateTime.o

$(OBJDIR_DEBUG)/__/CommonCpp/KSEventLog/KSEventLog.o: ../CommonCpp/KSEventLog/KSEventLog.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ../CommonCpp/KSEventLog/KSEventLog.cpp -o $(OBJDIR_DEBUG)/__/CommonCpp/KSEventLog/KSEventLog.o

$(OBJDIR_DEBUG)/__/CommonCpp/KSUtils/KSUtil.o: ../CommonCpp/KSUtils/KSUtil.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ../CommonCpp/KSUtils/KSUtil.cpp -o $(OBJDIR_DEBUG)/__/CommonCpp/KSUtils/KSUtil.o

$(OBJDIR_DEBUG)/__/CommonCpp/KSUtils/KSUtil20.o: ../CommonCpp/KSUtils/KSUtil20.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ../CommonCpp/KSUtils/KSUtil20.cpp -o $(OBJDIR_DEBUG)/__/CommonCpp/KSUtils/KSUtil20.o

$(OBJDIR_DEBUG)/__/CommonCpp/Platform/Linux/Platform.o: ../CommonCpp/Platform/Linux/Platform.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ../CommonCpp/Platform/Linux/Platform.cpp -o $(OBJDIR_DEBUG)/__/CommonCpp/Platform/Linux/Platform.o

$(OBJDIR_DEBUG)/__/CommonCpp/strfmt.o: ../CommonCpp/strfmt.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ../CommonCpp/strfmt.cpp -o $(OBJDIR_DEBUG)/__/CommonCpp/strfmt.o

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/__/CommonCpp/KSDateTime
	rm -rf $(OBJDIR_DEBUG)/__/CommonCpp/KSEventLog
	rm -rf $(OBJDIR_DEBUG)/__/CommonCpp/KSUtils
	rm -rf $(OBJDIR_DEBUG)/__/CommonCpp/Platform/Linux
	rm -rf $(OBJDIR_DEBUG)/__/CommonCpp
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/__/CommonCpp/KSDateTime || mkdir -p $(OBJDIR_RELEASE)/__/CommonCpp/KSDateTime
	test -d $(OBJDIR_RELEASE)/__/CommonCpp/KSEventLog || mkdir -p $(OBJDIR_RELEASE)/__/CommonCpp/KSEventLog
	test -d $(OBJDIR_RELEASE)/__/CommonCpp/KSUtils || mkdir -p $(OBJDIR_RELEASE)/__/CommonCpp/KSUtils
	test -d $(OBJDIR_RELEASE)/__/CommonCpp/Platform/Linux || mkdir -p $(OBJDIR_RELEASE)/__/CommonCpp/Platform/Linux
	test -d $(OBJDIR_RELEASE)/__/CommonCpp || mkdir -p $(OBJDIR_RELEASE)/__/CommonCpp
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/__/CommonCpp/KSDateTime/KSDateTime.o: ../CommonCpp/KSDateTime/KSDateTime.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ../CommonCpp/KSDateTime/KSDateTime.cpp -o $(OBJDIR_RELEASE)/__/CommonCpp/KSDateTime/KSDateTime.o

$(OBJDIR_RELEASE)/__/CommonCpp/KSEventLog/KSEventLog.o: ../CommonCpp/KSEventLog/KSEventLog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ../CommonCpp/KSEventLog/KSEventLog.cpp -o $(OBJDIR_RELEASE)/__/CommonCpp/KSEventLog/KSEventLog.o

$(OBJDIR_RELEASE)/__/CommonCpp/KSUtils/KSUtil.o: ../CommonCpp/KSUtils/KSUtil.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ../CommonCpp/KSUtils/KSUtil.cpp -o $(OBJDIR_RELEASE)/__/CommonCpp/KSUtils/KSUtil.o

$(OBJDIR_RELEASE)/__/CommonCpp/KSUtils/KSUtil20.o: ../CommonCpp/KSUtils/KSUtil20.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ../CommonCpp/KSUtils/KSUtil20.cpp -o $(OBJDIR_RELEASE)/__/CommonCpp/KSUtils/KSUtil20.o

$(OBJDIR_RELEASE)/__/CommonCpp/Platform/Linux/Platform.o: ../CommonCpp/Platform/Linux/Platform.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ../CommonCpp/Platform/Linux/Platform.cpp -o $(OBJDIR_RELEASE)/__/CommonCpp/Platform/Linux/Platform.o

$(OBJDIR_RELEASE)/__/CommonCpp/strfmt.o: ../CommonCpp/strfmt.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ../CommonCpp/strfmt.cpp -o $(OBJDIR_RELEASE)/__/CommonCpp/strfmt.o

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/__/CommonCpp/KSDateTime
	rm -rf $(OBJDIR_RELEASE)/__/CommonCpp/KSEventLog
	rm -rf $(OBJDIR_RELEASE)/__/CommonCpp/KSUtils
	rm -rf $(OBJDIR_RELEASE)/__/CommonCpp/Platform/Linux
	rm -rf $(OBJDIR_RELEASE)/__/CommonCpp
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

